apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubbles-backend
  namespace: argocd
spec:
  destination:
    namespace: bubbles-argorollouts
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: demo-apps/bubbles-backend/src/main/argorollouts
    repoURL: https://github.com/luisllm/demo-bubbles-progressive-delivery.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true